version: '3.3'
services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - SUBSCRIPTION_KEY=${cosmos_key}
      - GENERATE_ZIPPED=${generate_zipped}
      - TEMPLATE_FILE_NAME=${template_file_name}
      - VARS=${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

