version: '3.8'

services:
  pdf-engine-java:
    container_name: 'pdf-engine-java'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../java
    ports:
      - "60486:80"
  pdf-engine-node:
    container_name: 'pdf-engine-node'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../node
    ports:
      - "60487:80"