version: '3.8'

services:
  app:
    container_name: 'pdf-engine'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    ports:
      - "60486:80"
