oa3_spec: ./openapi/openapi_node.json
name: opex_pagopa-pdf-engine-node
location: West Europe
timespan: 5m
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
resource_type: api-management
action_groups:
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts:
    - api.platform.pagopa.it
  /shared/pdf-engine-node/v1/generate-pdf:
    response_time_threshold: 5 # Default: 1
    response_time_evaluation_frequency: 35 # Default: 10
    response_time_evaluation_time_window: 55 # Default: 20
    response_time_event_occurrences: 5 # Default: 1