oa3_spec: ./openapi/openapi_node.json
name: opex_pagopa-pdf-engine-node
location: West Europe
timespan: 5m
data_source: /subscriptions/26abc801-0d8f-4a6e-ac5f-8e81bcc09112/resourceGroups/pagopa-u-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-u-app-gw
resource_type: app-gateway
# data_source: /subscriptions/26abc801-0d8f-4a6e-ac5f-8e81bcc09112/resourceGroups/pagopa-u-api-rg/providers/Microsoft.ApiManagement/service/pagopa-u-apim
# resource_type: api-management
action_groups:
  - /subscriptions/26abc801-0d8f-4a6e-ac5f-8e81bcc09112/resourceGroups/pagopa-u-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/26abc801-0d8f-4a6e-ac5f-8e81bcc09112/resourceGroups/pagopa-u-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.uat.platform.pagopa.it
  base_path: "shared/pdf-engine-node/v1"
  endpoints:
    /generate-pdf:
      response_time_threshold: 6 # Default: 1
      response_time_evaluation_frequency: 35 # Default: 10
      response_time_evaluation_time_window: 55 # Default: 20
      response_time_event_occurrences: 5 # Default: 1