apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.32.0
appVersion: 1.4.3-PRDP-64-feat-add-elk-apm-configurations
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
