apiVersion: v2
name: pagopapdfengine
description: Microservice description
type: application
version: 0.132.0
appVersion: 2.10.21-1-PIDM-921-fix-spire-pdfa2a-conversion
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
