apiVersion: v2
name: pagopapdfengine
description: Microservice description
type: application
version: 0.110.0
appVersion: 2.10.3-VAS-1057-feat-add-infraction-partials
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
