apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.15.0
appVersion: 1.1.0-PRDP-49-ci-update-uat-chart
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
