apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.7.0
appVersion: 0.0.4-PRDP-40-fix-build-and-deploy
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
