apiVersion: v2
name: pagopa-pdf-engine
description: Microservice description
type: application
version: 0.48.0
appVersion: 1.9.0
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
