apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.41.0
appVersion: 1.6.0-PRDP-100-feat-add-playwright-engine
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
