apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.45.0
appVersion: 1.7.2
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
