apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.23.0
appVersion: 1.4.1-feat_update_helm_resources
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
