microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-pdf-engine
    tag: "2.5.6-2-PRDP-144-chore-reintroducing-aps-release-on-devops"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuuat.shared.internal.uat.platform.pagopa.it"
    path: /pagopa-pdf-engine/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "768Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "600m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 120 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: "uat"
    WEBSITE_SITE_NAME: "pagopapdfengine" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    HTML_TEMPLATE_FILE_NAME: "template"
    WORKING_DIRECTORY_PATH: "/temp"
    PDF_ENGINE_NODE_INFO_ENDPOINT: "https://api.uat.platform.pagopa.it/shared/pdf-engine-node/v1/info"
    PDF_ENGINE_NODE_GENERATE_ENDPOINT: "https://api.uat.platform.pagopa.it/shared/pdf-engine-node/v1/generate-pdf"
    ENABLE_ECS_CONSOLE: "true"
    CONSOLE_LOG_THRESHOLD: "DEBUG"
    CONSOLE_LOG_PATTERN: "%d{HH:mm:ss.SSS}[%thread]%-5level%logger{36}-%msg%n"
    CONSOLE_LOG_CHARSET: "UTF-8"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopapdfengineotl,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    JAVA_TOOL_OPTIONS: "-javaagent:/home/site/wwwroot/jmx_prometheus_javaagent-0.19.0.jar=12345:/home/site/wwwroot/config.yaml -javaagent:/home/site/wwwroot/opentelemetry-javaagent.jar"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: 'elastic-otel-token-header'
    PDF_ENGINE_NODE_SUBKEY: 'pdf-engine-node-subkey'
  keyvault:
    name: "pagopa-u-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
                  # nodeAffinity:
                  #   requiredDuringSchedulingIgnoredDuringExecution:
                  #     nodeSelectorTerms:
                  #       - matchExpressions:
                  #           - key: pdf
                  #             operator: In
                  #             values:
                  #               - 'true'
  # tolerations:
  #   - key: pdf
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-pdf-engine
        tag: "1.9.0"
        pullPolicy: Always
      envConfig:
      envSecret:
