name: Code Review

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_KEY: pagopa_pagopa-pdf-engine


permissions:
  id-token: write
  contents: read
  deployments: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-review-java:
    name: Code Review Java
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Code Review
        uses: ./.github/maven_code_review
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          project_key: ${{env.PROJECT_KEY}}
          jdk_version: 17
          maven_version: 3.9.3
          coverage_exclusions: "**/config/*,**/*Mock*,**/model/**,**/entity/*,**/producer/**,**/enumeration/**"
          cpd_exclusions: "**/model/**,**/entity/*"

  code-review-node:
    name: Code Review Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn --cwd ./node install

      - name: Start Node Server
        run: yarn --cwd ./node run start-detached

      - name: Run tests
        run: yarn --cwd ./node run test:coverage

      - name: SonarQube Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          GITHUB_TOKEN: ${{ inputs.github_token }}
        with:
          projectBaseDir: ./node
          args: >
            -Dsonar.organization=pagopa
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=./node/coverage/lcov-report/lcov.info
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ inputs.sonar_token }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: SonarQube Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          GITHUB_TOKEN: ${{ inputs.github_token }}
        with:
          projectBaseDir: ./node
          args: >
            -Dsonar.organization=pagopa
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=./node/coverage/lcov-report/lcov.info
            -Dsonar.branch.name=${{ github.head_ref }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ inputs.sonar_token }}

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run Service on Docker
        shell: bash
        id: run_service_docker
        run: |
          cd ./docker
          chmod +x ./run_docker.sh
          ./run_docker.sh local

      - name: Run Integration Tests
        shell: bash
        id: run_integration_test
        run: |
          export SUBKEY=${{ secrets.SUBKEY }}
          export CANARY=${{ inputs.canary }}
          export CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

          cd ./integration-test
          chmod +x ./run_integration_test.sh
          ./run_integration_test.sh local


  delete_github_deployments:
    runs-on: ubuntu-latest
    needs: smoke-test
    if: ${{ always() }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Delete Previous deployments
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        env:
          SHA_HEAD: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha}}
        with:
          script: |
            const { SHA_HEAD } = process.env

            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: SHA_HEAD
            });
            await Promise.all(
              deployments.data.map(async (deployment) => {
                await github.rest.repos.createDeploymentStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id,
                  state: 'inactive'
                });
                return github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id
                });
              })
            );